### ISSUE TITLE
Scheduled Task

### ISSUE THREAD

**Issue by goafer** [richardfleming/adpen#1]
Hi there,

I'm running the PowerShell script just amazingly when I do it manually through the PowerShell ISE.  But when I run it as a scheduled task, I am getting blank emails.  (Interestingly enough, the subject line is not blank and has the correct number of days left before expiration).

Any ideas?

**Comment by oded86w** [comment]
You can config  in program/script line 
powershell -file "G:\PasswordNotify\adpen.ps1"
And in Start in files
G:\PasswordNotify\

And it's work fine .
