### ISSUE TITLE
problem with test

### ISSUE THREAD

**Issue by oded86w** [richardfleming/adpen#3]
Hi . 
I  configured the script . 
I steel in test mode , But it's run very fast and I don't recive any mail or report .

**Comment by richardfleming** [comment]
paste your variables please.

**Comment by oded86w** [comment]
# Test mode, limiting queries to your Display Name and sending results to your email.
$testMode = $True
$testAddress = 'odedw@asaf.*****.***.il'
$testDisplayName = 'oded waiser'

# Set this to $False after configuring your variables
$preventScriptExecution = $False

I want to recive the email that need to send to user to check it .

**Comment by richardfleming** [comment]
Have you verified the `$smtpServer` variable has been set, and the mail server is functioning correctly?  Try to telnet to your SMTP server on port 25 and send a message that way to see if you get errors.

My script unfortunately doesn't do error handling.

Rich

**Comment by richardfleming** [comment]
One other thing that just occurred to me.  This script only looks for entries with a non-empty city field on the AD user account, if your organisation doesn't use the city field then you'll have a hard time.

You can remove that requirement by going to line 242 and removing `-and (l -like '*')`

Also, your display name needs to match your AD user account display name.

Cheers,

Rich

**Comment by oded86w** [comment]
Thank You , Its the city issue .
It also sends to people whose password has already expired a few days ago.
How do I change it to send only to people whose password has not expired yet.

**Comment by richardfleming** [comment]
That functionality was not written into the script as the whole point was to have users with expired passwords changed.  You will have to either modify the logic condition starting on line 263, or place their user name into the `$emailExempt` variable.

Cheers!
